name: Docker Image "base" CI
# ref: https://docs.docker.com/build/ci/github-actions/push-multi-registries/
on:
  workflow_dispatch: # on button click
  schedule:
    - cron: '11 0 */7 * *'
  push:
    paths:
      - base/**


jobs:
  build-base:
    runs-on: hk

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
          file: base/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cuhkhaosun/base:latest
